#!/bin/sh

source $OPENSHIFT_CARTRIDGE_SDK_BASH

ZABBIX_VERSION=2.0.8
ZABBIX_DIR=$( pwd )
BUILDROOT=$( mktemp -d )

pushd $BUILDROOT

curl -L -o zabbix-${ZABBIX_VERSION}.tar.gz http://sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/${ZABBIX_VERSION}/zabbix-${ZABBIX_VERSION}.tar.gz/download
tar -C $BUILDROOT -xzf zabbix-${ZABBIX_VERSION}.tar.gz

pushd zabbix-${ZABBIX_VERSION}
./configure --enable-agent --enable-ipv6 --with-libcurl --prefix $ZABBIX_DIR
make
make install
popd

popd
rm -rf $BUILDROOT

# Use .rb extension in source tree to make syntax highlighting happen
mv usr/bin/send-zabbix-data.rb usr/bin/send-zabbix-data
